### ISSUE TITLE
Occasional error with recording_tasks: "OperationalError: database is locked"

### ISSUE THREAD

**Issue by audevuilli** [acoupi/acoupi#45]
This issue is to log occasional errors occuring while acoupi program is running. The error is issue by pony.orm.core.TransactionError: OperationalError: database is locked. 

While the error does not stop the program from running, it let the recording file in the temporary folder (/run/shm). The file does not get deleted neither moved. This might cause issues after several days as files will accumulate in the /run/shm folder. 

Error Message: 
```
[2024-09-05 11:54:04,826: INFO/MainProcess] recording_task[23d54826-9779-4144-a27f-59d0756716c2]: Starting recording process.
[2024-09-05 11:54:04,829: INFO/MainProcess] recording_task[23d54826-9779-4144-a27f-59d0756716c2]: Recording audio
[2024-09-05 11:54:15,535: ERROR/MainProcess] Task recording_task[23d54826-9779-4144-a27f-59d0756716c2] raised unexpected: TransactionError('OperationalError: database is locked')
Traceback (most recent call last):
 ...
  File "/home/pi/acoupi-batdetect2/.venv/lib/python3.9/site-packages/acoupi/tasks/recording.py", line 45, in recording_task
    store.store_recording(recording)
  File "<string>", line 2, in store_recording
... 
    orm.commit()
  File "/home/pi/acoupi-batdetect2/.venv/lib/python3.9/site-packages/pony/orm/core.py", line 384, in commit
    transact_reraise(CommitException, exceptions)
... 
  File "/home/pi/acoupi-batdetect2/.venv/lib/python3.9/site-packages/pony/orm/dbproviders/sqlite.py", line 402, in commit
    DBAPIProvider.commit(provider, connection, cache)
  File "<string>", line 2, in commit
  File "/home/pi/acoupi-batdetect2/.venv/lib/python3.9/site-packages/pony/orm/dbapiprovider.py", line 72, in wrap_dbapi_exceptions
    raise OperationalError(e)
pony.orm.core.TransactionError: OperationalError: database is locked
[2024-09-05 11:54:19,826: INFO/MainProcess] Task recording_task[c863e553-0aa9-41a0-b0ea-0f7a2cedc044] received
```

Looking into the `store_recording`component and add try, except statement to handle this case. 
Either: 
1. Delete the recording
2. Wait for the db to be available

**Comment by audevuilli** [comment]
Still not fully resolve.
